/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.psp.api;

import com.example.psp.dto.MaterialDTO;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.List;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-12-03T17:27:47.624170900+02:00[Europe/Vilnius]")
@Validated
@Api(value = "material", description = "the material API")
public interface MaterialApi {

    default MaterialApiDelegate getDelegate() {
        return new MaterialApiDelegate() {};
    }

    /**
     * GET /material : Get a list of materials.
     *
     * @param pageSize Parameter to define how many records are in a page. (optional)
     * @param page Parameter to specify which page of records to return. (optional)
     * @return Success (status code 200)
     */
    @ApiOperation(value = "Get a list of materials.", nickname = "materialGet", notes = "", response = MaterialDTO.class, responseContainer = "List", tags={ "Material", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = MaterialDTO.class, responseContainer = "List") })
    @GetMapping(
        value = "/material",
        produces = { "application/json" }
    )
    default ResponseEntity<List<MaterialDTO>> materialGet(@ApiParam(value = "Parameter to define how many records are in a page.") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize,@ApiParam(value = "Parameter to specify which page of records to return.") @Valid @RequestParam(value = "page", required = false) Integer page) {
        return getDelegate().materialGet(pageSize, page);
    }


    /**
     * DELETE /material/{materialId} : Delete material by id.
     *
     * @param materialId  (required)
     * @return Success (status code 200)
     *         or If material with such id does not exist. (status code 404)
     */
    @ApiOperation(value = "Delete material by id.", nickname = "materialMaterialIdDelete", notes = "", tags={ "Material", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success"),
        @ApiResponse(code = 404, message = "If material with such id does not exist.") })
    @DeleteMapping(
        value = "/material/{materialId}"
    )
    default ResponseEntity<Void> materialMaterialIdDelete(@ApiParam(value = "",required=true) @PathVariable("materialId") Integer materialId) {
        return getDelegate().materialMaterialIdDelete(materialId);
    }


    /**
     * GET /material/{materialId} : Get material by Id.
     *
     * @param materialId  (required)
     * @return Success (status code 200)
     *         or If material with such id does not exist. (status code 404)
     */
    @ApiOperation(value = "Get material by Id.", nickname = "materialMaterialIdGet", notes = "", response = MaterialDTO.class, tags={ "Material", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = MaterialDTO.class),
        @ApiResponse(code = 404, message = "If material with such id does not exist.") })
    @GetMapping(
        value = "/material/{materialId}",
        produces = { "application/json" }
    )
    default ResponseEntity<MaterialDTO> materialMaterialIdGet(@ApiParam(value = "",required=true) @PathVariable("materialId") Integer materialId) {
        return getDelegate().materialMaterialIdGet(materialId);
    }


    /**
     * PUT /material/{materialId} : Update material by id.
     *
     * @param materialId  (required)
     * @param materialDTO  (optional)
     * @return Success (status code 200)
     *         or If some material details are missing. (status code 400)
     *         or If material with such id does not exist. (status code 404)
     */
    @ApiOperation(value = "Update material by id.", nickname = "materialMaterialIdPut", notes = "", tags={ "Material", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success"),
        @ApiResponse(code = 400, message = "If some material details are missing."),
        @ApiResponse(code = 404, message = "If material with such id does not exist.") })
    @PutMapping(
        value = "/material/{materialId}",
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> materialMaterialIdPut(@ApiParam(value = "",required=true) @PathVariable("materialId") Integer materialId,@ApiParam(value = ""  )  @Valid @RequestBody(required = false) MaterialDTO materialDTO) {
        return getDelegate().materialMaterialIdPut(materialId, materialDTO);
    }


    /**
     * POST /material : Create material.
     *
     * @param materialDTO  (optional)
     * @return Success (status code 200)
     *         or If some material details are missing. (status code 400)
     */
    @ApiOperation(value = "Create material.", nickname = "materialPost", notes = "", tags={ "Material", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success"),
        @ApiResponse(code = 400, message = "If some material details are missing.") })
    @PostMapping(
        value = "/material",
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> materialPost(@ApiParam(value = ""  )  @Valid @RequestBody(required = false) MaterialDTO materialDTO) {
        return getDelegate().materialPost(materialDTO);
    }

}
